# 错误上报
https://blog.csdn.net/chjj0904/article/details/81288766

## 一.捕捉错误上报的
### 1.try catch
- try catch只能捕获到运行时的非异步错误，而语法错误和异步错误就捕捉不到
- 不能捕捉定时器，promise的错误
- 还有一点就是try..catch比较消耗性能，能少用的最好

``` js
// 可以捕捉
try {
	a()
} catch (error) {
	console.log(error)
}

// 不能捕捉 ---定时器
try {
	setTimeout(() => {
		a()
	}, 400)
} catch (error) {
	console.log(error)
}

// 不能捕捉 ---- promise

try {
	new Promise((resolve, reject) => {
		reject()
	})
} catch (error) {
	console.log(error)
}

```

### 2.promise.catch
- 捕捉promise 的错误

``` js

new Promise((resolve, reject) => {
	a()
}).catch((e) => {
	console.log(e)
})
```

### 3.定时器的错误捕捉
- window.onerror
- window.addEventListener('error'）


### 4.window.onerror
-   window.onerror 函数只有在返回 true 的时候，异常才不会向上抛出，否则即使是知道异常的发生控制台还是会显示 Uncaught Error: xxxxx。
-   window.onerror 是无法捕获到网络异常的错误,资源加载错误

``` js
window.onerror = function (msg, url, row, col, error) {
	console.log('我知道错误了');
	console.log({
		msg, url, row, col, error
	})
	return true;
};
```

### 4.window.addEventListener('error')
- 监听js运行时错误事件，会比window.onerror先触发
- 不能阻止默认事件处理函数的执行，但可以全局捕获资源加载异常的错误

### 5.window.addEventListener("unhandledrejection")
- 处理没有被promise.catch捕获的promise错误

``` js
window.addEventListener("unhandledrejection", function(errMsg) {
	console.log('errMsg',errMsg)
}, true)
  
new Promise(() => {
	a()
})
```







